// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Ancestor from "@rescriptbr/ancestor/src/Ancestor.bs.js";

function App(Props) {
  return React.createElement(Ancestor.Box.make, {
              bgColor: [
                Ancestor.xs({
                      NAME: "hex",
                      VAL: "#cecece"
                    }),
                Ancestor.md({
                      NAME: "hex",
                      VAL: "#000"
                    })
              ],
              p: [Ancestor.xs(4)],
              width: [Ancestor.xs({
                      NAME: "pct",
                      VAL: 100.0
                    })],
              height: [Ancestor.xs({
                      NAME: "pct",
                      VAL: 100.0
                    })],
              children: React.createElement(Ancestor.Base.make, {
                    color: [
                      Ancestor.xs({
                            NAME: "hex",
                            VAL: "#fafafa"
                          }),
                      Ancestor.md({
                            NAME: "hex",
                            VAL: "#cecece"
                          })
                    ],
                    fontSize: [Ancestor.xs({
                            NAME: "px",
                            VAL: 32
                          })],
                    children: "ReScript + Tauri + Rust > Electrons"
                  })
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
