// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Root element not found.");
} else {
  ReactDom.render(React.createElement(App.make, {}), root);
}

export {
  
}
/* root Not a pure module */
